# Datascience career track: course 1 : Intro to Python

### lists

In [0]:
x = [1,2,3,4,'x','y',[9,0,'z']]
print(x)
y = x
y[0]=101
print(x,y) #x also changes

[1, 2, 3, 4, 'x', 'y', [9, 0, 'z']]
[101, 2, 3, 4, 'x', 'y', [9, 0, 'z']] [101, 2, 3, 4, 'x', 'y', [9, 0, 'z']]


In [0]:
print(x)

z=list(x) #x wont change
z[0]=99
print(z,x)

w=x[:] #x wont change
w[0]=78
print(w,x)

[101, 2, 3, 4, 'x', 'y', [9, 0, 'z']]
[99, 2, 3, 4, 'x', 'y', [9, 0, 'z']] [101, 2, 3, 4, 'x', 'y', [9, 0, 'z']]
[78, 2, 3, 4, 'x', 'y', [9, 0, 'z']] [101, 2, 3, 4, 'x', 'y', [9, 0, 'z']]


### + operator

In [0]:
#various ways + operator works
i = 98
s = "aysha"
l = [1,2,0]

print(i+i,s+s,l+l)

196 ayshaaysha [1, 2, 0, 1, 2, 0]


### list del

In [0]:
print(l)
del(l[2])
print(l)

[1, 2, 0]
[1, 2]


### functions

In [0]:
#closest integer or to number of digits specified
round(1.235) , round(1.235,1) , round(1.235,2) , round(1.235,3)

(1, 1.2, 1.24, 1.235)

In [0]:
help(round)

Help on built-in function round in module builtins:

round(...)
    round(number[, ndigits]) -> number
    
    Round a number to a given precision in decimal digits (default 0 digits).
    This returns an int when called with one argument, otherwise the
    same type as the number. ndigits may be negative.



In [0]:
# [, ndigits] is optional arguments
?round

### methods: functions that belong to specific objects

In [0]:
ls = ["aysha","aysha",90,90,91]

ls.index("aysha") , ls.count("aysha") , ls.count(90)


(0, 2, 2)

In [0]:
st = "aysha"

st.capitalize() , st.replace("a","ok"), st.index('y') , st.upper()

('Aysha', 'okyshok', 1, 'AYSHA')

### numpy

In [0]:
## python list = numpy array
## can perform calculations over entire arrays , and fast

import numpy as np
ls = [1,5.7,7,22,3.9]
npls=np.array(ls)

ls, npls

([1, 5.7, 7, 22, 3.9], array([ 1. ,  5.7,  7. , 22. ,  3.9]))

In [0]:
npls2=np.array([90,79.9,89,7,78])

npls.shape , npls2.shape

((5,), (5,))

In [0]:
npls/npls2**2 ##tadaa

array([1.23456790e-04, 8.92855744e-04, 8.83726802e-04, 4.48979592e-01,
       6.41025641e-04])

In [0]:
## arrays can contain a SINGLE type only

np.array([16,'aysha',True]) #all turned to string

array(['16', 'aysha', 'True'], dtype='<U21')

In [0]:
# + doesnt act like in lists, its actually adds
npls+npls2

array([91. , 85.6, 96. , 29. , 81.9])

In [0]:
#slicing
npls[:2]

array([1. , 5.7])

In [0]:
#conditionals / masking
npls[npls>9] , npls>9

(array([22.]), array([False, False, False,  True, False]))

### numpt attributes : .att --> no () at the end

In [12]:
## e.g
ls=[[1,5,6],
   [9,0,9],
   [9,8,2]]
nl = np.array(ls)
nl.shape

(3, 3)

In [0]:
nl[0][1] , nl[0,1]  #ways to index

(5, 5)

In [0]:
nl[:,1:3]

array([[5, 6],
       [0, 9],
       [8, 2]])

### numpy stats

In [0]:
import numpy as np

In [0]:
nl = np.array([[1,5,6],
               [9,0,9],
               [9,8,2]])

In [18]:
np.mean(nl[:,0]) , np.median(nl[:,0]) , np.std(nl[:,0])

(6.333333333333333, 9.0, 3.7712361663282534)

In [19]:
np.corrcoef(nl[:,1],nl[:,0])

array([[ 1.        , -0.14285714],
       [-0.14285714,  1.        ]])

In [20]:
height = np.round(np.random.normal(1.75,0.02,5000),2) #mean, std, size
weight = np.round(np.random.normal(60.32,15,5000),2)
city = np.column_stack((height, weight))
height[:3] , weight[:3] , city[:3]

(array([1.75, 1.76, 1.75]),
 array([57.93, 62.99, 89.93]),
 array([[ 1.75, 57.93],
        [ 1.76, 62.99],
        [ 1.75, 89.93]]))